---
packages:
  - acpi
  - acpitool
  - aspell-en
  - axel
  - calibre
  - cgdb
  - chkrootkit
  - chrome-gnome-shell
  - clang
  - cloc
  - cmake
  - crudini
  - ctags
  - curl
  - dconf-editor
  - diffstat
  - direnv
  - elinks
  - exfat-utils
  - fdupes
  - ffmpeg
  - fish
  - flatpak
  - fzf
  - gimp
  - git
  - gnome-tweak-tool
  - golang
  - golang-go
  - gparted
  - gthumb
  - htop
  - inkscape
  - iptraf-ng
  - isync
  - jq
  - kcachegrind
  - kitty
  - kitty-doc
  - kitty-terminfo
  - llvm
  - lshw
  - lynis
  - make
  - mc
  - meld
  - meson
  - moreutils
  - most
  - mplayer
  - msmtp
  - ncdu
  - ncftp
  - neovim
  - nethogs
  - newsboat
  - ntpdate
  - openssh-server
  - openttd
  - p7zip
  - pandoc
  - poedit
  - proxychains-ng
  - python3-glanceclient
  - python3-openstackclient
  - python3-neovim
  - python3-novaclient
  - python3-pip
  - python3-psutil
  - python3-swiftclient
  - rclone
  - reptyr
  - rkhunter
  - seahorse-nautilus
  - sen
  - siege
  - simple-scan
  - sloccount
  - smartmontools
  - sqlitebrowser
  - stow
  - strace
  - swaks
  - thunderbird
  - tig
  - tlp
  - tmux
  - tor
  - tree
  - unrar
  - urlview
  - vagrant
  - valgrind
  - vnstat
  - wavemon
  - wget
  - yamllint
  - zeal
