distribution_packages:
  - NetworkManager-tui
  - ack
  - arandr
  - aspell-en
  - axel
  - calibre
  - cgdb
  - chkrootkit
  - clang
  - clang-analyzer
  - cloc
  - crudini
  - ctags
  - ctags-etags
  - elinks
  - fdupes
  - feh
  - fish
  - flameshot
  - fzf
  - gdb-gdbserver
  - gimp
  - gnome-dictionary
  - gnome-tweaks
  - gparted
  - graphviz
  - gstreamer1-plugins-bad-free-extras
  - gstreamer1-plugins-bad-freeworld
  # - gstreamer1-plugins-bad-nonfree
  - gstreamer1-plugins-ugly
  - hplip-gui
  - htop
  # - https://go.skype.com/skypeforlinux-64.rpm
  - hub
  - icat
  - iptraf-ng
  - jq
  - keepassxc
  - kpcli
  - libasan
  - libjpeg-turbo-devel
  - libreoffice-langpack-fr
  - libtiff-devel
  - libwebp-devel
  - libxml2-devel
  - libxslt-devel
  - light
  - links
  - lshw
  - lynx
  - mc
  - moreutils
  - most
  - mplayer
  - msmtp
  - ncdu
  - ncftp
  # - neomutt
  - neovim
  - nethogs
  - npm
  - ntpdate
  - openttd-docs
  - openttd-opengfx
  - p7zip
  - pandoc
  - pavucontrol
  - poedit
  - postgresql-devel
  - proxychains-ng
  - python3-devel
  - python3-docker
  - python3-pip
  - redhat-rpm-config
  - redshift
  - redshift-gtk
  - rkhunter
  - rofi
  - rofi-themes
  - seahorse
  - seahorse-nautilus
  - seahorse-sharing
  - sen
  - sloccount
  - sqliteman
  - stow
  - strace
  - swaks
  - sway
  - the_silver_searcher
  - thunderbird
  - tidy
  - tig
  - tmux
  - tor
  - unrar
  - urlview
  - vim
  - vinagre
  - vlc
  - vlc-extras
  - vnstat
  - wavemon  # Network tool
  - zeal