distribution_packages:
  - ack-grep
  - acpi-call-dkms
  - acpitail
  - airgraph-ng
  - apt-listchanges
  - aptitude
  - build-essential
  - chromium-browser
  - exfat-fuse
  - fancontrol
  - firefox-geckodriver
  - gdbserver
  - hardinfo
  - libavcodec-extra
  - libavcodec-extra58
  - libbz2-dev
  - libcanberra-gtk-module
  - libffi-dev 
  - libheif-examples
  - liblzma-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libvirt-daemon-system
  - lua-nvim
  - neomutt
  - openttd-data
  - openttd-opengfx
  - openttd-openmsx
  - openttd-opensfx
  - python3-dnspython
  - python3-venv
  - sqlite3
  - tk-dev
  - torbrowser-launcher
  - tp-smapi-dkms
  - weather-util
  - wifite
  - xz-utils
  - zlib1g-dev
