---
- name: Install Laptop
  vars_files:
    - secrets.yml
    - vars/main.yml
  hosts: localhost
  roles:
    - role: packages
      become: true
      tags: [packages]
    - role: docker
      become: true
    - flatpak
    - gnome
    - python
    - user_space
    - role: git_repositories
      tags: [git]
