---
- name: Install Laptop
  vars_files:
    - secrets.yml
    - vars/main.yml
  hosts: localhost
  roles:
    - role: packages
      become: true

    - flatpak
    - role: gnome
      become_user: stephane

    - python
    - user_space
    - role: git_repositories
      tags: [git]
