---
- name: Install Laptop
  vars_files:
    - secrets.yml
  hosts: localhost
  roles:
    - role: packages
      become: yes

    - flatpak
    - gnome
    - python
    - user_space
    - role: git_repositories
      tags: [git]