- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
- name: Install Common Packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python3-psutil
    - neovim
    - tig
    - zeal
    - tig
    - neovim
    - fish