---
- name: Install Specific Packages for Fedora
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Specific Packages for Debian
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Load the common packages
  include_vars: commons.yml

- name: Load the specific packages
  include_vars: vars-{{ ansible_os_family }}.yml

- name: Install Packages
  package:
    name: "{{ packages + distribution_packages }}"
    state: present

- name: Install snaps app
  snap:
    name:
      - bw
