---
- name: Add Repo for MS Teams
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/ms-teams stable main
    state: present

- name: Install Teams
  apt:
    name:
      - teams
    update_cache: true
    state: present
