---
- name: Add APT Key for Microsoft Teams
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Microsoft Repositories
  apt_repository:
    filename: "{{ item }}"
    repo: "deb [arch=amd64] {{repository}}/{{item}} stable main"
  loop: "{{ repositories }}"
  vars:
    repository: "https://packages.microsoft.com/repos"
    repositories:
      - ms-teams
      - vscode

- name: Install Microsoft Applications
  apt:
    pkg: [code, teams]
    update_cache: true
    state: present
