- name: Install Packages
  dnf:
    name:
      - python3-pip
      - python3-psutil
      - neovim
      - tig
      - zeal
    state: present

- name: Install Network Tools
  dnf:
    name:
      - NetworkManager-tui
    state: present
