- name: Install PyEnv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv/

- name: Install PipX
  pip:
    name: pipx
    extra_args: --user --upgrade

- name: Install Python Packages
  command: "pipx install {{ item }}"
  loop:
    - ansible-lint
    - cookiecutter
    - doc2dash
    - docker-compose
    - httpie
    - molecule
    - poetry
    - pygments
    - ranger-fm
    - stormssh
    - tmuxp
    - virtualfish
    - youtube-dl
