- name: Install PipX
  pip:
    name: pipx
    extra_args: --user --upgrade

- name: Install Python Packages
  command: "~/.local/bin/pipx install {{ item }}"
  loop:
    - ansible-lint
    - cookiecutter
    - doc2dash
    - docker-compose
    - httpie
    - molecule
    - poetry
    - pygments
    - ranger-fm
    - stormssh
    - tmuxp
    - youtube-dl

- name: install virtualfish
  pip:
    name: virtualfish
    extra_args: --user --upgrade
