---
- name: Change User
  become: yes
  user:
    name: "{{ user.unix }}"
    comment: "{{ user.name }}"
    shell: "{{ user.shell }}"

- name: Set default editor to nvim
  become: yes
  shell: "update-alternatives --set editor /usr/bin/nvim"
  ignore_errors: yes