- name: Check if ~/.config/fish exists
  stat:
    path: ~/.config/fish
  register: status

- name: Create ~/.config/fish
  file:
    path: ~/.config/fish
    state: directory
    owner: "{{ user.id }}"
    group: "{{ user.id }}"
  when: status.stat.isdir is not defined

- name: Create the fish config file
  template:
    src: fish.config.fish.j2
    dest: ~/.config/fish/config.fish

- name: Clone oh-my-fish repo
  git:
    repo: https://github.com/oh-my-fish/oh-my-fish
    dest: /tmp/omf
    clone: yes
  tags: [fish]

- name: Install oh-my-fish
  command: >
    /tmp/omf/bin/install
    --yes
    --offline
    --noninteractive
    --path=~/.local/share/omf
    --config=~/.config/omf

  tags: [fish]
  # ignore_errors: yes

# - name: Install tmux/plugins/bobthefish
#   command: "omf install bobthefish"
#   tags: [fish]