---
- name: Check if ~/.config/fish exists
  stat:
    path: ~/.config/fish
  register: status

- name: Create ~/.config/fish
  file:
    path: ~/.config/fish
    state: directory
    owner: "{{ user.unix }}"
    group: "{{ user.unix }}"
  when: status.stat.isdir is not defined

- name: Create the fish config file
  template:
    src: fish.config.fish.j2
    dest: ~/.config/fish/config.fish

- name: Clone oh-my-fish repo
  git:
    repo: https://github.com/oh-my-fish/oh-my-fish
    dest: /tmp/omf

- name: Install oh-my-fish
  command: >
    /tmp/omf/bin/install
    --yes
    --offline
    --noninteractive
    --path=~/.local/share/omf
    --config=~/.config/omf

- name: Install tmux/plugins/bobthefish
  git:
    repo: https://github.com/oh-my-fish/theme-bobthefish
    dest: ~/.local/share/omf/themes/bobthefish

- name: Set bobthefish
  copy:
    content: >
      bobthefish
    dest: ~/.config/omf/theme
