---
- name: Create the kitty config directory
  file:
    path: ~/.config/kitty/
    state: directory

- name: Configure kitty
  copy:
    src: kitty.conf
    dest: ~/.config/kitty/kitty.conf

    # - name: Define kitty as default x-terminal-emulator
    #   become: yes
    #   shell: update-alternatives --set x-terminal-emulator /usr/bin/kitty
