---
- import_tasks: configure_user.yml
- import_tasks: pyenv.yml
  tags: [pyenv, python, user]
- import_tasks: neovim.yml
- import_tasks: gitconfig.yml
- import_tasks: fish.yml
  tags: [fish, config]
- import_tasks: tmux.yml
- import_tasks: kitty.yml
  tags: [kitty, terminal-emulator]
- import_tasks: zeal.yml
  tags: [zeal]
- import_tasks: mbsync.yml
  tags: [mbsync, config]
- import_tasks: hub.yml
  tags: [hub]
- import_tasks: restic.yml
  tags: [restic]
- import_tasks: yq.yml
  tags: [yq]
- import_tasks: pup.yml
  tags: [pup]
- import_tasks: terraform.yml
  tags: [terraform]