---
- name: Create ~/.mbsync
  file:
    path: ~/.mbsync
    state: directory

- name: Create the mbsync files
  template:
    src: mbsync.j2
    dest: "~/.mbsync/{{ item.user }}"
  loop: "{{ mailboxes }}"
  no_log: true

- name: Create the maildirs
  file:
    path: "~/mail/{{ item.user }}"
    state: directory
    recurse: true
  loop: "{{ mailboxes }}"
  no_log: true

- name: Add crontabs
  cron:
    name: mail for {{ item.user }}
    user: stephane
    minute: "*/15"
    job: "/usr/bin/mbsync -a -c ~/.mbsync/{{ item.user }}"
  loop: "{{ mailboxes }}"
  no_log: true
