---
- name: Check if directory for vim-plug alreasy exist
  stat:
    path: ~/.local/share/nvim/site/autoload/
  register: status
- name: Create Directori for nvim
  file:
    path: ~/.local/share/nvim/site/autoload/
    state: directory
    owner: stephane
    group: stephane
  when: status.stat.isdir is not defined

- name: Download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
  when: status.stat.isdir is not defined

- name: Check if ~/.config/nvim exists
  stat:
    path: ~/.config/nvim
  register: status

- name: Create ~/.config/nvim
  file:
    path: ~/.config/nvim
    state: directory
    owner: stephane
    group: stephane
  when: status.stat.isdir is not defined

- name: Generate a NeoVIM  config from the template
  template:
    src: init.vim.j2
    dest: ~/.config/nvim/init.vim

- name: Install neovim for python2
  command: "~/.pyenv/versions/{{neovim.python2}}/bin/pip install neovim"

- name: Install neovim for python3
  command: "~/.pyenv/versions/{{neovim.python3}}/bin/pip install neovim"

- name: Install the NeoVIM plugins
  command: nvim +PlugInstall! +qall

- name: Update all the NeoVIM plugins
  command: nvim +PlugUpdate! +qall
