---
- name: pup already installed?
  stat:
    path: ~/.local/bin/pup
  register: st_pup

- name: Download pup
  unarchive:
    src: https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
    dest: ~/.local/bin/
    remote_src: true
  when: not st_pup.stat.exists

- name: Set right access
  file:
    path: ~/.local/bin/pup
    mode: u+x
  when: not st_pup.stat.exists