---
- name: Install PyEnv
  import_role:
    name: avanov.pyenv
  vars:
    pyenv_path: "{{ansible_env.HOME}}/.pyenv"
    pyenv_update_git_install: true
    pyenv_python_versions: [2.7.18, 3.8.3]
    pyenv_virtualenvs:
      - venv_name: nvim-py2
        py_version: "2.7.18"
      - venv_name: nvim-py3
        py_version: "3.8.3"
  tags: [pyenv]
