- name: Add FlatHub Repo
  flatpak_remote:
    method: "{{ flatpak_method }}"
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  tags: [applications, flatpak]

- name: Intall Packages
  flatpak:
    name: "{{ item }}"
    state: present
    method: "{{ flatpak_method }}"
  loop: "{{ flatpak_packages }}"
  tags: [applications, flatpak]