---
- name: Install Gnome Extenions
  import_role:
    name: jaredhocutt.gnome_extensions
  vars:
    gnome_extension_ids:
      - 19
      - 770
      - 964
  tags: [gnome, gnome-extensions]

- name: Download Gnome Transparent Theme
  git:
    repo: https://github.com/mrbrownstone07/Transparent-Shell-Theme
    dest: ~/.themes/Transparent-Shell-Theme
  tags: [gnome]

- name: Configure Gnome
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ dconf|dict2items }}"
  tags: [gnome, dconf]

