---
- name: Remove the dependencies
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    update_cache: true

- name: Install the dependencies
  apt:
    pkg: [apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common]
    state: present

- name: Add Signing Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable"
    state: present

- name: Install Docker
  apt:
    pkg: [docker-ce, docker-ce-cli, containerd.io]
    update_cache: yes

- name: Add User to Docker group
  user:
    name: stephane
    append: yes
    groups: docker
